<?php

/* 
 * Copyright (C) 2015 Kévin Grenèche < kevin.greneche at openhivemanager.org >
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ColonieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColonieRepository extends EntityRepository
{
    public function getListByExploitation($page=1, $maxperpage=10, $exploitation)
    {
        $q = $this->createQueryBuilder('c')
                  ->leftJoin('c.exploitation','e')
                  ->addSelect('e')
                  ->where('e.id = :id')
                  ->setParameter('id',$exploitation);
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function countByExploitation($exploitation)
    {
        return $this->createQueryBuilder('c')
                    ->select('COUNT(c)')
                    ->leftJoin('c.exploitation','e')
                    ->where('e.id = :id')              
                    ->setParameter('id',$exploitation)
                    ->getQuery()
                    ->getSingleScalarResult();
    }   
      
}
