<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ColonnieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColonnieRepository extends EntityRepository
{
    public function getListByExploitation($page=1, $maxperpage=10, $exploitation)
    {
        $q = $this->createQueryBuilder('c')
                  ->leftJoin('c.exploitation','e')
                  ->addSelect('e')
                  ->where('e.id = :id')
                  ->setParameter('id',$exploitation);
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function countByExploitation($exploitation)
    {
        return $this->createQueryBuilder('c')
                    ->select('COUNT(c)')
                    ->leftJoin('c.exploitation','e')
                    ->where('e.id = :id')              
                    ->setParameter('id',$exploitation)
                    ->getQuery()
                    ->getSingleScalarResult();
    }   
      
}
