<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends EntityRepository
{
    public function queryfindByRucherId($rucher)
    {
        return $this->createQueryBuilder('emplacement')
                    ->leftJoin('emplacement.rucher', 'rucher')
                    ->addSelect('rucher')
                    ->leftJoin('emplacement.ruche', 'ruche')
                    ->addSelect('ruche')                
                    ->where('rucher.id = :rucher') 
                    ->andWhere('ruche.emplacement is NULL')
                    ->setParameter('rucher',$rucher);
    }

    public function findByRucherId($rucher)
    {
        return $this->queryfindByRucherId($rucher)
                    ->getQuery()
                    ->getArrayResult();
    }    
}
