<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RecolteRucherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecolteRucherRepository extends EntityRepository
{
    public function getListByRucher($page=1, $maxperpage=10, $rucher)
    {
        $q = $this->createQueryBuilder('recolte')
                  ->leftJoin('recolte.rucher','rucher')               
                  ->addSelect('rucher')
                  ->where('rucher.id = :id')
                  ->setParameter('id',$rucher);
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function countByRucher($rucher)
    {
        return $this->createQueryBuilder('recolte')
                    ->select('COUNT(recolte)')
                    ->leftJoin('recolte.rucher','rucher')
                    ->where('rucher.id = :id')              
                    ->setParameter('id',$rucher)
                    ->getQuery()
                    ->getSingleScalarResult();
    }    
}
