<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecolteRucherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecolteRucherRepository extends EntityRepository
{
    public function getListByRucher($rucher)
    {
        return $this->createQueryBuilder('recolte')
                    ->leftJoin('recolte.rucher','rucher')               
                    ->addSelect('rucher')
                    ->where('rucher.id = :id')
                    ->setParameter('id',$rucher->getId())
                    ->getQuery();
    }
    
   
}
