<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RucherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RucherRepository extends EntityRepository
{
    public function getListByExploitation($page=1, $maxperpage=10, $exploitation)
    {
        $q = $this->createQueryBuilder('r')
                  ->leftJoin('r.exploitation','e')
                  ->addSelect('e')
                  ->where('e.id = :id')
                  ->setParameter('id',$exploitation);
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function countByExploitation($exploitation)
    {
        return $this->createQueryBuilder('r')
                    ->select('COUNT(r)')
                    ->leftJoin('r.exploitation','e')
                    ->where('e.id = :id')
                    ->setParameter('id',$exploitation)
                    ->getQuery()
                    ->getSingleScalarResult();
    }  
    
    public function getRucherByExploitation($id, $exploitation)
    {
        return $this->createQueryBuilder('r')
                    ->leftJoin('r.exploitation','e')
                    ->addSelect('e')
                    ->where('e.id = :exploitation')
                    ->andWhere('r.id = :id')
                    ->setParameter('exploitation',$exploitation)
                    ->setParameter('id',$id)
                    ->getQuery()
                    ->getSingleResult();
    }    
}
