<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RucherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RucherRepository extends EntityRepository
{
    public function getList($page=1, $maxperpage=10)
    {
        $q = $this->_em->createQueryBuilder()
             ->select('rucher')
             ->from('KGBeekeepingManagementBundle:Rucher','rucher');
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function getNbRucherTotal()
    {
        return $this->_em->createQueryBuilder()
                ->select('count(rucher.id)')
                ->from('KGBeekeepingManagementBundle:Rucher','rucher')
                ->getQuery()
                ->getSingleScalarResult();
    }    
}
