<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousTypeRucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypeRucheRepository extends EntityRepository
{
    public function queryfindByTypeId($type)
    {
        return $this->createQueryBuilder('soustype')
                    ->leftJoin('soustype.type', 'type')
                    ->addSelect('type')
                    ->where('type.id = :type')                 
                    ->setParameter('type',$type);
    }
    
    public function findByTypeId($type)
    {
        return $this->queryfindByTypeId($type)
                    ->getQuery()
                    ->getArrayResult();
    }     
}
