<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function getList($page=1, $maxperpage=10)
    {
        $q = $this->_em->createQueryBuilder()
             ->select('stock')
             ->from('KGBeekeepingManagementBundle:Stock','stock');
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function getNbStockTotal()
    {
        return $this->_em->createQueryBuilder()
                ->select('count(stock.id)')
                ->from('KGBeekeepingManagementBundle:Stock','stock')
                ->getQuery()
                ->getSingleScalarResult();
    }
}
