<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TranshumanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranshumanceRepository extends EntityRepository
{
    public function getListByColonie($colonie)
    {
        return $this->createQueryBuilder('t')
                    ->leftJoin('t.colonie','colonie')
                    ->addSelect('colonie')
                    ->where('colonie.id = :id')
                    ->setParameter('id',$colonie->getId())
                    ->getQuery();                    
    }   
}
