<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends EntityRepository
{
    public function getListByRuche($page=1, $maxperpage=10, $ruche)
    {
        $q = $this->createQueryBuilder('visite')
                  ->leftJoin('visite.ruche','ruche')
                  ->addSelect('ruche')
                  ->where('ruche.id = :id')
                  //->andWhere('ruche.supprime = false')
                  ->setParameter('id',$ruche);
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function countByRuche($ruche)
    {
        return $this->createQueryBuilder('visite')
                    ->select('COUNT(visite)')
                    ->leftJoin('visite.ruche','ruche')
                    ->where('ruche.id = :id')
                    //->andWhere('ruche.supprime = false')                
                    ->setParameter('id',$ruche)
                    ->getQuery()
                    ->getSingleScalarResult();
    }      
}
