<?php

namespace KG\BeekeepingManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends EntityRepository
{
    public function getListByColonnie($page=1, $maxperpage=10, $colonnie)
    {
        $q = $this->createQueryBuilder('visite')
                  ->leftJoin('visite.colonnie','colonnie')
                  ->addSelect('colonnie')
                  ->where('colonnie.id = :id')
                  ->andWhere('visite.supprime = false')
                  ->setParameter('id',$colonnie);
        
        $q->setFirstResult(($page-1)*$maxperpage)
          ->setMaxResults($maxperpage);
        
        return new Paginator($q);
    }
    
    public function countByColonnie($colonnie)
    {
        return $this->createQueryBuilder('visite')
                    ->select('COUNT(visite)')
                    ->leftJoin('visite.colonnie','colonnie')
                    ->where('colonnie.id = :id')
                    ->andWhere('visite.supprime = false')                
                    ->setParameter('id',$colonnie)
                    ->getQuery()
                    ->getSingleScalarResult();
    }      
}
